# Generated by Django 4.0.3 on 2022-10-27 17:29

from django.db import migrations
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_editorjs_fields.fields.EditorJsJSONField(),
        ),
    ]
